import pandas as pd
from jinja2 import Environment, FileSystemLoader
import os
from datetime import datetime
import matplotlib.pyplot as plt
import base64
from io import BytesIO

class ReportEngine:
    def __init__(self, template_dir='templates', output_dir='output'):
        self.template_dir = template_dir
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(template_dir, exist_ok=True)
        self.env = Environment(loader=FileSystemLoader(template_dir))

    def create_sample_data(self):
        data = {
            'Category': ['Revenue', 'Cost of Sales', 'Operating Expenses', 'Tax', 'Net Profit'],
            'Q1': [100000, 60000, 20000, 5000, 15000],
            'Q2': [120000, 70000, 22000, 6000, 22000],
            'Q3': [110000, 65000, 21000, 5500, 18500],
            'Q4': [150000, 85000, 25000, 8000, 32000]
        }
        return pd.DataFrame(data)

    def generate_chart(self, df):
        plt.figure(figsize=(10, 6))
        df.set_index('Category').T.plot(kind='bar', stacked=True)
        plt.title('Financial Performance Overview')
        plt.ylabel('Amount ($)')
        plt.xlabel('Quarter')
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        
        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
        plt.close()
        return image_base64

    def generate_html_report(self, data_file=None):
        if data_file:
            df = pd.read_csv(data_file)
        else:
            df = self.create_sample_data()

        chart_data = self.generate_chart(df)
        template = self.env.get_template('report_template.html')
        
        report_content = template.render(
            title="Automated Financial Report",
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            table=df.to_html(classes='table table-striped', index=False),
            chart_image=chart_data
        )

        output_path = os.path.join(self.output_dir, 'financial_report.html')
        with open(output_path, 'w') as f:
            f.write(report_content)
        
        print(f"Report generated successfully: {output_path}")
        return output_path

if __name__ == "__main__":
    # Create a default template if it doesn't exist
    os.makedirs('templates', exist_ok=True)
    with open('templates/report_template.html', 'w') as f:
        f.write("""
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <style>
        body { padding: 50px; background-color: #f8f9fa; }
        .report-container { background: white; padding: 40px; border-radius: 15px; shadow: 0 0 20px rgba(0,0,0,0.1); }
        .header { border-bottom: 2px solid #dee2e6; margin-bottom: 30px; padding-bottom: 10px; }
        .chart-container { margin-top: 40px; text-align: center; }
    </style>
</head>
<body>
    <div class="container report-container">
        <div class="header">
            <h1>{{ title }}</h1>
            <p class="text-muted">Generated on: {{ date }}</p>
        </div>
        
        <h3>Summary Data</h3>
        <div class="table-responsive">
            {{ table | safe }}
        </div>
        
        <div class="chart-container">
            <h3>Visual Analysis</h3>
            <img src="data:image/png;base64,{{ chart_image }}" class="img-fluid shadow rounded" alt="Financial Chart">
        </div>
        
        <div class="footer mt-5 pt-3 border-top text-center text-muted">
            <p>Generated by ReportFlow Automation Engine</p>
        </div>
    </div>
</body>
</html>
        """)

    engine = ReportEngine()
    engine.generate_html_report()
